---
# yamllint disable rule:colons
#                             _                                       _
#   ___   _ __   ___   _ _   | |_   ___  __ _   ___   _ _    ___   __| |  ___
#  / _ \ | '_ \ / -_) | ' \  |  _| (_-< / _` | |___| | ' \  / _ \ / _` | / -_)
#  \___/ | .__/ \___| |_||_|  \__| /__/ \__, |       |_||_| \___/ \__,_| \___|
#        |_|                            |___/
# #############################################################################
# CHECK
# #############################################################################
#check:

# #############################################################################
# SNIPPETS
# #############################################################################
# --- command snippets clog <snippet> --------------------------------------------
# --- IMPORTANT: command snippets stream their output {for terminals}
# --- IMPORTANT:   shell snippets buffer their output (batch mode)
#
#    These will take priority over any scripts you load, so a snippet in this
#    section will make a script of the same command name invisible.
#    e.g.
#      commandsnippets:
#        watch: devtool server --port=1234 --mode=DEBUG 2>logs/dbg
#
#      can be run with the command
#          clog watch
#    con
snippets:
  git:
    vcode: cat releases.yaml|grep version|head -1|grep -oE '[0-9]+\.[0-9]+\.[0-9]'
  # --- project snippets:  clog project <snippet> ---------------------------
  # typically used for global tool version propagation, node version etc.
  # project:
  #   needs:
  #     go-version: "1.23.0"
  #     hugo-version: "0.136.0"
  #     node-version: "21.7.0"

# #############################################################################
#                 _
#   _ _    __ _  (_)  _ _   __ __
#  | ' \  / _` | | | | ' \  \ \ /
#  |_||_| \__, | |_| |_||_| /_\_\
#         |___/
# #############################################################################
# --- nginx installation configuration ----------------------------------------
# these defaults correspond to the apt package defaults
nginx:
  configPath: embed
  shellsnippets: []
  folder:
    available: /etc/nginx/sites-available/
    enabled: /etc/nginx/sites-enabled/

# #############################################################################
#
#   ___ __ __  __
#  (_-< \ V / / _|
#  /__/  \_/  \__|
# #############################################################################
# --- svc is a chi based website using cloglib/clogsvc ----------------------------
svc:
  configPath: embed
  port: 11998
  configFileName: server.config.yaml
  # use the main env variable name unless overriden by the svc for web ops
  env:
    dbConnectionString: DB_CON_STR_CLOGSVC

  db:
    type: sqlite
    #if no connection details specified then use env.dbConnectionString
    defaultPageLimit: 20
    defaultSort: CreatedAt
  homeFolder: set-at-runtime
  version:
    short: "0.0.0"
    long: 0.0.0-gitcommit

  # webhook handling
  # format: https://some-host.dns/a/hook/hookType/{source}/{project}/{semver}
  # format: https://some-host.dns/a/hook/cicd/gitlab-deploy/$PROJECT/$vCODE
  hookprefix: "/hook"
  hooks:
    # params for responding to /hook/website/{id}
    - prefix: /website/staging/{id}
      ruleName: Test staging website
      something: Another property
      somevalue: 600
      somearray: [1, 2, 3, 4]
# #############################################################################
